on:
  workflow_dispatch:
    inputs:
      astring:
        type: string
      achoice:
        # default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      abool:
        type: boolean
      anenv:
        type: environment
        
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "astring: -z $astring"
          echo "achoice: -z $achoice"
          echo "abool: -z $abool"
          echo "anenv: -z $anenv"
          
          if [ -z "${anenv+x}" ]; then
            echo "anenv is null (unset)"
          elif [ -z "$anenv" ]; then
            echo "anenv is set, but empty string"
          else
            echo "anenv has a value: $anenv"
          fi
          
        env:
          astring: ${{ inputs.astring }}
          achoice: ${{ inputs.achoice }}
          abool: ${{ inputs.abool }}
          anenv: ${{ inputs.anenv }}
