on:
  workflow_dispatch:
    inputs:
      astring:
        type: string
      achoice:
        # default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      abool:
        type: boolean
      anenv:
        type: environment
        
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |

          echo null
          
          if [ -z "${astring+x}" ]; then
            echo "astring is null (unset)"
          elif [ -z "$astring" ]; then
            echo "astring is set, but empty string"
          else
            echo "astring has a value: $astring"
          fi
          
          if [ -z "${achoice+x}" ]; then
            echo "achoice is null (unset)"
          elif [ -z "$achoice" ]; then
            echo "achoice is set, but empty string"
          else
            echo "achoice has a value: $achoice"
          fi
          
          if [ -z "${abool+x}" ]; then
            echo "abool is null (unset)"
          elif [ -z "$abool" ]; then
            echo "abool is set, but empty string"
          else
            echo "abool has a value: $abool"
          fi
          
          if [ -z "${anenv+x}" ]; then
            echo "anenv is null (unset)"
          elif [ -z "$anenv" ]; then
            echo "anenv is set, but empty string"
          else
            echo "anenv has a value: $anenv"
          fi
          
        env:
          astring: ${{ inputs.astring }}
          achoice: ${{ inputs.achoice }}
          abool: ${{ inputs.abool }}
          anenv: ${{ inputs.anenv }}
